server:
  port: 7002


spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://47.98.41.195:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: lingyun@123


eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #是否向注册中心注册自己
    fetchRegistry: false #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
        #      设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://localhost:7002/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka/  #集群版（相互注册，相互守望）
#      defaultZone: http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka  #注册多台


  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.lingyun.springcloud.entities

