server:
  port: 8006


spring:
  application:
    name: cloud-provider-payment
#consul注册中心
  cloud:
    consul:
      host: 47.98.41.195
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        #consul红叉解决
        heartbeat:
          enabled: true
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://47.98.41.195:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: lingyun@123

