server:
  port: 80


spring:
  application:
    name: cloud-comsumer-order
  cloud:
    zookeeper:
      connect-string: 47.98.41.195:2181
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://47.98.41.195:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: lingyun@123
